### ISSUE TITLE
Two issues of OutlineGen.m

### ISSUE THREAD

**Issue by LeoXLiu-DS** [majroy/CM_CMM#1]
1.  In line 73 -75 of `OutlineGen.m`,  both `miny` and `maxy` are assumed to be positive when generating y; however, if either of them is negative, it would cause the range of generated y to be less than the sample dimension. Therefore, to fix this issue, these scripts may be modified to: 
`miny=min(A{end}(:,2)); maxy=max(A{end}(:,2));`
`if maxy > 0`
    `maxy=1.1*maxy;`
`else`
    `maxy=0.9*maxy;`
`end`
`if miny > 0`
    `miny=0.9*miny;` 
`else`
    `miny=1.1*miny;`
`end`
`y=[miny maxy];`

2. It seems that `OutlineGen.m` could give an error when processing the artificial data, e.g. the z-direction measurements of the cutting surface are all equal (perfect flat) or the x- or y-direction measurments are equal for the perimeter measurements. This would not be an issue for real measured data; however, I am wondering whether it should be noted in case somebody want to taste the code with some virtual data (exactly like what we have done :)).

**Comment by majroy** [comment]
On issue 1 - code has been changed. On issue 2 - taken under advisement, but sample data is provided in the repo,.
